package SourceCode.OOPs_08.OOP_4;

public class ObjectDemo {

    int num1, num2;
    public ObjectDemo(int num1, int num2) {
        this.num1 = num1;
        this.num2 = num2;
    }

    // toString is a method, which convert the words in "" to string and print it
    // in the terminal.
    @Override
    public String toString() {
        return super.toString();
    }

    // finalize is a method, which used for garbage collection. When it reaches the
    // certain value, it will automatically remove the unused space.
    @Override
    protected void finalize() throws Throwable {
        super.finalize();
    }

    // it is the randomly generated number code, generated by java.
    @Override
    public int hashCode() {
        return super.hashCode();
    }

    // equals is the method used to check the content of the object file.
    @Override
    public boolean equals(Object obj) {
        return super.equals(obj);
    }

    public static void main(String[] args) {
        ObjectDemo obj1 = new ObjectDemo(12, 55);
        ObjectDemo obj2 = obj1;

//        System.out.println(obj1 + " " + obj2);
//        SourceCode.OOPs_08.OOP_4.ObjectDemo@279f2327
//        SourceCode.OOPs_08.OOP_4.ObjectDemo@2ff4acd0


//        Here, == will check for the address of the both objects.
        if (obj1 == obj2) {
            System.out.println("equal");
        }

//        Here, equals method check for the values of the both objects.
        if (obj1.equals(obj2)) {
            System.out.println("equal");
        }

    }
}
